export const ADD_CONSTRUCTOR_INGREDIENT: 'ADD_CONSTRUCTOR_INGREDIENT' = 'ADD_CONSTRUCTOR_INGREDIENT'
export const DELETE_CONSTRUCTOR_INGREDIENT: 'DELETE_CONSTRUCTOR_INGREDIENT' = 'DELETE_CONSTRUCTOR_INGREDIENT'

export const ADD_CONSTRUCTOR_BUN: 'ADD_CONSTRUCTOR_BUN' = 'ADD_CONSTRUCTOR_BUN'
export const DELETE_ALL_CONSTRUCTOR_INGREDIENTS: 'DELETE_ALL_CONSTRUCTOR_INGREDIENTS' = 'DELETE_ALL_CONSTRUCTOR_INGREDIENTS'

export const REPLACE_CONSTRUCTOR_INGREDIENT: 'REPLACE_CONSTRUCTOR_INGREDIENT' = 'REPLACE_CONSTRUCTOR_INGREDIENT'