export const GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST' = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS' = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAILED: 'GET_ORDERS_FAILED' = 'GET_ORDERS_FAILED'

export const POPUP_ADD_ORDER: 'POPUP_ADD_ORDER' = 'POPUP_ADD_ORDER'
export const POPUP_DELETE_ORDER: 'POPUP_ADD_ORDER' = 'POPUP_ADD_ORDER'