export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST'

export const POPUP_ADD_INGREDIENT: 'POPUP_ADD_INGREDIENT' = 'POPUP_ADD_INGREDIENT'
export const POPUP_DELETE_INGREDIENT: 'POPUP_DELETE_INGREDIENT' = 'POPUP_DELETE_INGREDIENT'