export const TOGGLE_POPUP_INGREDIENT: 'TOGGLE_POPUP_INGREDIENT' = 'TOGGLE_POPUP_INGREDIENT' 
export const TOGGLE_POPUP_ORDER: 'TOGGLE_POPUP_ORDER' = 'TOGGLE_POPUP_ORDER'
export const TOGGLE_POPUP_FEED_ORDER: 'TOGGLE_POPUP_FEED_ORDER' = 'TOGGLE_POPUP_FEED_ORDER'