export const PASSWORD_FORGOT_REQUEST: 'PASSWORD_FORGOT_REQUEST' = 'PASSWORD_FORGOT_REQUEST'
export const PASSWORD_FORGOT_SUCCESS: 'PASSWORD_FORGOT_SUCCESS' = 'PASSWORD_FORGOT_SUCCESS'
export const PASSWORD_FORGOT_FAILED: 'PASSWORD_FORGOT_FAILED' = 'PASSWORD_FORGOT_FAILED'

export const PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST' = 'PASSWORD_RESET_REQUEST'
export const PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS' = 'PASSWORD_RESET_SUCCESS'
export const PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED' = 'PASSWORD_RESET_FAILED'

export const USER_REGISTRATION_REQUEST: 'USER_REGISTRATION_REQUEST' = 'USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS' = 'USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_FAILED: 'USER_REGISTRATION_FAILED' = 'USER_REGISTRATION_FAILED'

export const USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST' = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS' = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED: 'USER_LOGIN_FAILED' = 'USER_LOGIN_FAILED'

export const USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST' = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS' = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED' = 'USER_LOGOUT_FAILED'

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST'
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED'

export const GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST' = 'GET_USER_INFO_REQUEST' 
export const GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS' = 'GET_USER_INFO_SUCCESS' 
export const GET_USER_INFO_FAILED: 'GET_USER_INFO_FAILED' = 'GET_USER_INFO_FAILED' 

export const SET_USER_INFO_REQUEST: 'SET_USER_INFO_REQUEST' = 'SET_USER_INFO_REQUEST'
export const SET_USER_INFO_SUCCESS: 'SET_USER_INFO_SUCCESS' = 'SET_USER_INFO_SUCCESS'
export const SET_USER_INFO_FAILED: 'SET_USER_INFO_FAILED' = 'SET_USER_INFO_FAILED'